### ISSUE TITLE
Workflow auto starts after first push

### ISSUE THREAD

**Issue by saadusufzai** [bcanseco/github-contribution-graph-action#12]
im using back fill graph action. after the fist commit the workflow starts and then ends successfully but after an interval it starts again and then again , it keeps on committing 

im using this code below 
` on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: you@youremail.com # replace me
        MAX_DAYS: 365
        MIN_COMMITS_PER_DAY: 1
        MAX_COMMITS_PER_DAY: 5
`

**Comment by bcanseco** [comment]
hey Saad, not sure what's going wrong here. Any chance you could post your full `.yml` file(s) or link one of the actions runs that keep going?

**Comment by saadusufzai** [comment]
Thanks for your reply buddy.
I really dont know what the problem was. I deleted the repo and then created a new one with the same steps. now its working fine .
