### ISSUE TITLE
Does not work since 2023 start

### ISSUE THREAD

**Issue by danteteder** [bcanseco/github-contribution-graph-action#19]
Does not work since 2023 start

**Comment by bcanseco** [comment]
@danteteder Could you please double check that the workflow is enabled?
>Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow#enabling-a-workflow

If it's not disabled and you can confirm it's running, could you please post the output of a run that isn't working?

**Comment by nevwizurai** [comment]
![Screenshot 2023-01-17 071911](https://user-images.githubusercontent.com/44189782/212783771-143aea4b-8d91-4033-9996-71173b39acb4.png)
not sure if it's the same cause, but mine failed with these errors

**Comment by nevwizurai** [comment]
![Screenshot 2023-01-17 071911](https://user-images.githubusercontent.com/44189782/212784002-4e298166-372d-407b-a793-8aed7972e68b.png)
not sure if it's the same cause, but mine failed with these errors

**Comment by bcanseco** [comment]
@nevwizurai looks like GitHub recently added customizable permissions for the `GITHUB_TOKEN` and it seems to be read-only for new repos. Could you try changing yours to read and write and let me know if it works?
<img width="762" src="https://user-images.githubusercontent.com/18430599/212792273-b108321f-869b-4db9-a6c9-ed02a4f7203c.png">

**Comment by nevwizurai** [comment]
@bcanseco 
![image](https://user-images.githubusercontent.com/44189782/212836129-e6ce45ef-ab68-41f2-a958-2710ed5fe255.png)
I see, the problem was in the token permission. thank you :D

**Comment by bcanseco** [comment]
Added a note about this to the README in 0550b5854eb04ffe3e1159420ebc1e7a73290eda
